### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by slauger** [slauger/puppet-metricbeat#1]
- Fix documentation
- Write Spec/Unit tests

**Comment by zlanyi** [comment]
Hi,
any news here for releases? Could you please add a tag?

Thanks

Regards,
Zoltan

**Comment by slauger** [comment]
Hi @zlanyi,

i created an inital v1.0.0 tag and released the module on the Puppet Forge.

https://forge.puppet.com/slauger/metricbeat

Travis builds are currently failing because of https://github.com/puppetlabs/pdk-templates/issues/179. I won't fix this - this will hopefully be resolved within the next pdk-template release
